# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: graph.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='graph.proto',
  package='ada',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0bgraph.proto\x12\x03\x61\x64\x61\"\xf9\x01\n\tAttribute\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\x12\x0e\n\x06values\x18\x04 \x03(\t\x12\x10\n\x08\x61nimated\x18\x05 \x01(\x08\x12\r\n\x05\x43lass\x18\x06 \x01(\t\x12%\n\x04type\x18\x07 \x01(\x0e\x32\x17.ada.Attribute.AdaTypes\x12#\n\x05\x61lias\x18\x08 \x01(\x0b\x32\x14.ada.Attribute.Alias\x1a\x15\n\x05\x41lias\x12\x0c\n\x04name\x18\x01 \x01(\t\",\n\x08\x41\x64\x61Types\x12\t\n\x05\x41LIAS\x10\x00\x12\t\n\x05INPUT\x10\x01\x12\n\n\x06OUTPUT\x10\x02\"\x92\x01\n\x05Queue\x12\r\n\x05order\x18\x01 \x01(\x05\x12\x1e\n\x05nodes\x18\x02 \x03(\x0b\x32\x0f.ada.Queue.Node\x1aZ\n\x04Node\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tfull_name\x18\x02 \x01(\t\x12\"\n\nattributes\x18\x03 \x03(\x0b\x32\x0e.ada.Attribute\x12\r\n\x05\x43lass\x18\x04 \x01(\t\"e\n\x05Scene\x12\x19\n\x05queue\x18\x01 \x03(\x0b\x32\n.ada.Queue\x12\x1d\n\x04root\x18\x02 \x01(\x0b\x32\x0f.ada.Scene.Root\x1a\"\n\x04Root\x12\x0b\n\x03\x66ps\x18\x01 \x01(\x02\x12\r\n\x05views\x18\x02 \x03(\tb\x06proto3')
)



_ATTRIBUTE_ADATYPES = _descriptor.EnumDescriptor(
  name='AdaTypes',
  full_name='ada.Attribute.AdaTypes',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ALIAS', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INPUT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OUTPUT', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=226,
  serialized_end=270,
)
_sym_db.RegisterEnumDescriptor(_ATTRIBUTE_ADATYPES)


_ATTRIBUTE_ALIAS = _descriptor.Descriptor(
  name='Alias',
  full_name='ada.Attribute.Alias',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ada.Attribute.Alias.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=203,
  serialized_end=224,
)

_ATTRIBUTE = _descriptor.Descriptor(
  name='Attribute',
  full_name='ada.Attribute',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ada.Attribute.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label', full_name='ada.Attribute.label', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='ada.Attribute.value', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='ada.Attribute.values', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='animated', full_name='ada.Attribute.animated', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Class', full_name='ada.Attribute.Class', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='ada.Attribute.type', index=6,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alias', full_name='ada.Attribute.alias', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ATTRIBUTE_ALIAS, ],
  enum_types=[
    _ATTRIBUTE_ADATYPES,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=270,
)


_QUEUE_NODE = _descriptor.Descriptor(
  name='Node',
  full_name='ada.Queue.Node',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ada.Queue.Node.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='full_name', full_name='ada.Queue.Node.full_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='attributes', full_name='ada.Queue.Node.attributes', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Class', full_name='ada.Queue.Node.Class', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=329,
  serialized_end=419,
)

_QUEUE = _descriptor.Descriptor(
  name='Queue',
  full_name='ada.Queue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='order', full_name='ada.Queue.order', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nodes', full_name='ada.Queue.nodes', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_QUEUE_NODE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=273,
  serialized_end=419,
)


_SCENE_ROOT = _descriptor.Descriptor(
  name='Root',
  full_name='ada.Scene.Root',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fps', full_name='ada.Scene.Root.fps', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='views', full_name='ada.Scene.Root.views', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=488,
  serialized_end=522,
)

_SCENE = _descriptor.Descriptor(
  name='Scene',
  full_name='ada.Scene',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='queue', full_name='ada.Scene.queue', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='root', full_name='ada.Scene.root', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SCENE_ROOT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=421,
  serialized_end=522,
)

_ATTRIBUTE_ALIAS.containing_type = _ATTRIBUTE
_ATTRIBUTE.fields_by_name['type'].enum_type = _ATTRIBUTE_ADATYPES
_ATTRIBUTE.fields_by_name['alias'].message_type = _ATTRIBUTE_ALIAS
_ATTRIBUTE_ADATYPES.containing_type = _ATTRIBUTE
_QUEUE_NODE.fields_by_name['attributes'].message_type = _ATTRIBUTE
_QUEUE_NODE.containing_type = _QUEUE
_QUEUE.fields_by_name['nodes'].message_type = _QUEUE_NODE
_SCENE_ROOT.containing_type = _SCENE
_SCENE.fields_by_name['queue'].message_type = _QUEUE
_SCENE.fields_by_name['root'].message_type = _SCENE_ROOT
DESCRIPTOR.message_types_by_name['Attribute'] = _ATTRIBUTE
DESCRIPTOR.message_types_by_name['Queue'] = _QUEUE
DESCRIPTOR.message_types_by_name['Scene'] = _SCENE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Attribute = _reflection.GeneratedProtocolMessageType('Attribute', (_message.Message,), dict(

  Alias = _reflection.GeneratedProtocolMessageType('Alias', (_message.Message,), dict(
    DESCRIPTOR = _ATTRIBUTE_ALIAS,
    __module__ = 'graph_pb2'
    # @@protoc_insertion_point(class_scope:ada.Attribute.Alias)
    ))
  ,
  DESCRIPTOR = _ATTRIBUTE,
  __module__ = 'graph_pb2'
  # @@protoc_insertion_point(class_scope:ada.Attribute)
  ))
_sym_db.RegisterMessage(Attribute)
_sym_db.RegisterMessage(Attribute.Alias)

Queue = _reflection.GeneratedProtocolMessageType('Queue', (_message.Message,), dict(

  Node = _reflection.GeneratedProtocolMessageType('Node', (_message.Message,), dict(
    DESCRIPTOR = _QUEUE_NODE,
    __module__ = 'graph_pb2'
    # @@protoc_insertion_point(class_scope:ada.Queue.Node)
    ))
  ,
  DESCRIPTOR = _QUEUE,
  __module__ = 'graph_pb2'
  # @@protoc_insertion_point(class_scope:ada.Queue)
  ))
_sym_db.RegisterMessage(Queue)
_sym_db.RegisterMessage(Queue.Node)

Scene = _reflection.GeneratedProtocolMessageType('Scene', (_message.Message,), dict(

  Root = _reflection.GeneratedProtocolMessageType('Root', (_message.Message,), dict(
    DESCRIPTOR = _SCENE_ROOT,
    __module__ = 'graph_pb2'
    # @@protoc_insertion_point(class_scope:ada.Scene.Root)
    ))
  ,
  DESCRIPTOR = _SCENE,
  __module__ = 'graph_pb2'
  # @@protoc_insertion_point(class_scope:ada.Scene)
  ))
_sym_db.RegisterMessage(Scene)
_sym_db.RegisterMessage(Scene.Root)


# @@protoc_insertion_point(module_scope)
